### ISSUE TITLE
ERROR Script load failed: node_modules\hexo-theme-vivia\scripts\color-generate.js Error: Cannot find module 'js-yaml'

### ISSUE THREAD

**Issue by azurefox1008** [saicaca/hexo-theme-vivia#1]
你好呀，打扰了，我按照README中的步骤安装后，使用hexo g生成静态页面时会提示上述错误。换用git clone下载到themes文件夹下也是color-generate.js加载失败+Cannot find module 'js-yaml'，但安装其他主题一切正常，不知道是哪一步操作出了问题？
静待回复，非常感谢！

**Comment by azurefox1008** [comment]
> 你好，尝试先执行一下 `npm install js-yaml --save` 再执行 `hexo g` 看看能不能解决问题？

谢谢！执行过了，按这个方法把缺失的module都安装了，不再报错Cannot find module，就是还有两个报错

ERROR
ReferenceError: D:\Program Files\myBlog\node_modules\hexo-theme-vivia\layout\post.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

D:\Program Files\myBlog\node_modules\hexo-theme-vivia\layout\_partial\article.ejs:17
    15|           </div>
    16|           <div class="wordcount need-seperator meta-info">
 >> 17|             <%- symbolsCount(post) %> <%- __('words') %>
    18|           </div>
    19|         </div>
    20|         <%- partial('post/tag') %>

symbolsCount is not defined
    at eval (eval at compile (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:673:12), <anonymous>:38:7)
    at article (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:673:12), <anonymous>:10:17)
    at post (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Program Files\myBlog\node_modules\.store\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Program Files\myBlog\node_modules\.store\bluebird@3.7.2\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
ERROR
ReferenceError: D:\Program Files\myBlog\node_modules\hexo-theme-vivia\layout\index.ejs:2
    1| <% page.posts.each(function(post){ %>
 >> 2|   <%- partial('_partial/article', {post: post, index: true}) %>
    3| <% }) %>
    4| <% if (page.total > 1){ %>
    5|   <nav id="page-nav">

D:\Program Files\myBlog\node_modules\hexo-theme-vivia\layout\_partial\article.ejs:17
    15|           </div>
    16|           <div class="wordcount need-seperator meta-info">
 >> 17|             <%- symbolsCount(post) %> <%- __('words') %>
    18|           </div>
    19|         </div>
    20|         <%- partial('post/tag') %>

symbolsCount is not defined
    at eval (eval at compile (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:673:12), <anonymous>:38:7)
    at article (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:673:12), <anonymous>:13:17)
    at _Query.forEach (D:\Program Files\myBlog\node_modules\.store\warehouse@4.0.2\node_modules\warehouse\lib\query.js:36:7)
    at eval (eval at compile (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:673:12), <anonymous>:10:19)
    at index (D:\Program Files\myBlog\node_modules\.store\ejs@3.1.9\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Program Files\myBlog\node_modules\.store\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Program Files\myBlog\node_modules\.store\bluebird@3.7.2\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Program Files\myBlog\node_modules\.store\hexo@6.3.0\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

似乎是没找到symbolsCount这个变量，在别的主题下找到一个看起来很像的（？）☛https://fingthinking.github.io/2017/08/05/Hexo%E5%8F%8AAnisina%E4%BD%BF%E7%94%A8%E5%BF%83%E5%BE%97/#%E9%97%AE%E9%A2%982-%E4%BD%BF%E7%94%A8Anisina%E4%B8%BB%E9%A2%98%EF%BC%8Chexo-new-page-xxx%E4%B9%8B%E5%90%8E%EF%BC%8Chexo-g%E6%8A%A5%E9%94%99%EF%BC%9F

**Comment by saicaca** [comment]
这应该是因为使用了将 `vivia` 放在 `themes` 下的安装方式，这样 hexo 启动时似乎不会自动安装主题的依赖。
进入 `themes/vivia` 目录下运行 `npm install` 应该能解决问题，但还是建议通过 npm 安装这个主题。

**Comment by azurefox1008** [comment]
> 嗯嗯(●'◡'●) 我尝试用 cnpm 安装也遇到了一样的问题，`symbolsCount is not defined` 应该是 cnpm 没有正确下载 `hexo-word-counter` 这个依赖导致的

安装`hexo-word-counter`就OK了，谢谢谢谢！差点以为自己用不上这么好看的主题了，实在麻烦你了(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)
