### ISSUE TITLE
关于无法成功使用 vivia，/layout/index.ejs  /layout/_partial/article.ejs 报错

### ISSUE THREAD

**Issue by Acerkaio** [saicaca/hexo-theme-vivia#15]
错误信息如下：
```
Unhandled rejection TypeError: /home/acerkaio/桌面/blog/blognew/themes/vivia/layout/index.ejs:2
    1| <% page.posts.each(function(post){ %>
 >> 2|   <%- partial('_partial/article', {post: post, index: true}) %>
    3| <% }) %>
    4| <% if (page.total > 1){ %>
    5|   <nav id="page-nav">

/home/acerkaio/桌面/blog/blognew/themes/vivia/layout/_partial/article.ejs:4
    2| 
    3| <article id="<%= post.layout %>-<%= post.slug %>" class="h-entry article article-type-<%= post.layout %>" itemprop="blogPost" itemscope itemtype="https://schema.org/BlogPosting">
 >> 4|   <% if (is_post() || theme.home.style == 'detail') { %>
    5|     <%- partial('post/gallery') %>
    6|   <% } %> 
    7|   <div class="article-inner">

Cannot read properties of null (reading 'home')
    at eval ("/home/acerkaio/桌面/blog/blognew/themes/vivia/layout/_partial/article.ejs":20:31)
    at article (/home/acerkaio/桌面/blog/blognew/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/acerkaio/桌面/blog/blognew/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/home/acerkaio/桌面/blog/blognew/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/home/acerkaio/桌面/blog/blognew/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/home/acerkaio/桌面/blog/blognew/themes/vivia/layout/index.ejs":13:17)
    at _Query.forEach (/home/acerkaio/桌面/blog/blognew/node_modules/warehouse/lib/query.js:36:7)
    at eval ("/home/acerkaio/桌面/blog/blognew/themes/vivia/layout/index.ejs":10:19)
    at index (/home/acerkaio/桌面/blog/blognew/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/acerkaio/桌面/blog/blognew/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/acerkaio/桌面/blog/blognew/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/acerkaio/桌面/blog/blognew/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/acerkaio/桌面/blog/blognew/node_modules/bluebird/js/release/util.js:16:23)
    at /home/acerkaio/桌面/blog/blognew/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/acerkaio/桌面/blog/blognew/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:504:12)
    at resume_ (node:internal/streams/readable:1007:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```
我使用 `hexo init` 后下载 vivia 主题 放入 themes 文件夹，更改 _config.yml 文件 `hexo s` 后报错。(已新建 about 页面)

求助。

**Comment by saicaca** [comment]
读取不到主题配置导致的。是不是没有把主题配置文件 `_config.vivia.yml` 复制到 Hexo 项目的根目录？（看 README 的安装过程第二步）

**Comment by Acerkaio** [comment]
是的，我的问题 /kk
