### ISSUE TITLE
ERROR Script load failed: node_modules/hexo-theme-vivia/scripts/color-generate.js

### ISSUE THREAD

**Issue by JnChan823** [saicaca/hexo-theme-vivia#18]
hexo new page about
INFO  Validating config
ERROR Script load failed: node_modules/hexo-theme-vivia/scripts/color-generate.js
/cjdata/my_blogger/blog/node_modules/colorjs.io/dist/color.cjs:349
			format.type ||= "function";
			            ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at req (/cjdata/my_blogger/blog/node_modules/hexo/lib/hexo/index.js:292:23)
    at /cjdata/my_blogger/blog/node_modules/hexo-theme-vivia/scripts/color-generate.js:1:80
    at /cjdata/my_blogger/blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/cjdata/my_blogger/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)

**Comment by saicaca** [comment]
出现 `SyntaxError: Unexpected token '||='` 可能是因为你安装的 node.js 版本过低了，更新到 v15.0.0 之后的版本试试

**Comment by JnChan823** [comment]
谢谢啦，安装新版本之后，已解决该问题
