### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by alazytag** [saicaca/hexo-theme-vivia#39]
请问hexo g总会出现类似这样的报错可能是什么原因呢
谢谢 nodejs不是很熟悉

```
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 553 ms
ERROR 
TypeError: /mnt/d/ubuntu-tmp/zengguanning/themes/vivia/layout/page.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

/mnt/d/ubuntu-tmp/zengguanning/themes/vivia/layout/_partial/article.ejs:5
    3| 
    4| <article id="<%= post.layout %>-<%= post.slug %>" class="h-entry article article-type-<%= post.layout %>" itemprop="blogPost" itemscope itemtype="https://schema.org/BlogPosting">
 >> 5|   <% if (is_post() || theme.home.style == 'detail') { %>
    6|     <%- partial('post/gallery') %>
    7|   <% } %> 
    8|   <div class="article-inner">

Cannot read properties of undefined (reading 'style')
    at eval ("/mnt/d/ubuntu-tmp/zengguanning/themes/vivia/layout/_partial/article.ejs":23:36)
    at article (/mnt/d/ubuntu-tmp/zengguanning/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/mnt/d/ubuntu-tmp/zengguanning/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/mnt/d/ubuntu-tmp/zengguanning/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/mnt/d/ubuntu-tmp/zengguanning/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/mnt/d/ubuntu-tmp/zengguanning/themes/vivia/layout/page.ejs":10:17)
    at page (/mnt/d/ubuntu-tmp/zengguanning/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/mnt/d/ubuntu-tmp/zengguanning/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/mnt/d/ubuntu-tmp/zengguanning/node_modules/hexo/lib/theme/view.js:39:17)
    at /mnt/d/ubuntu-tmp/zengguanning/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/mnt/d/ubuntu-tmp/zengguanning/node_modules/bluebird/js/release/util.js:16:23)
    at /mnt/d/ubuntu-tmp/zengguanning/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/mnt/d/ubuntu-tmp/zengguanning/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by saicaca** [comment]
应该是因为没读取到主题配置，建议检查有没有按照 README 的安装流程在博客根目录创建 `_config.vivia.yml`

**Comment by alazytag** [comment]
已经解决 谢谢
